<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        h1 {
            color: #1e40af;
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 10px;
        }
        .header {
            margin-bottom: 30px;
        }
        .info {
            background-color: #f3f4f6;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .info-row {
            margin: 8px 0;
            font-size: 14px;
        }
        .info-label {
            font-weight: bold;
            color: #1e40af;
            display: inline-block;
            width: 150px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table thead {
            background-color: #dbeafe;
        }
        table th {
            padding: 12px;
            text-align: left;
            font-weight: bold;
            color: #1e40af;
            border-bottom: 2px solid #3b82f6;
        }
        table td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
        }
        table tbody tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .period-header {
            background-color: #dbeafe;
            padding: 12px;
            margin-top: 20px;
            margin-bottom: 10px;
            border-left: 4px solid #3b82f6;
            font-weight: bold;
            color: #1e40af;
        }
        .period-count {
            color: #666;
            font-size: 12px;
            font-weight: normal;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            font-size: 12px;
            color: #666;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Library Report</h1>
        <div class="info">
            <div class="info-row">
                <span class="info-label">Report Type:</span>
                <strong>{{ $type }}</strong>
            </div>
            <div class="info-row">
                <span class="info-label">Period:</span>
                <strong>{{ $date_from }} to {{ $date_to }}</strong>
            </div>
            <div class="info-row">
                <span class="info-label">Department:</span>
                <strong>{{ $filters['dept'] }}</strong>
            </div>
            <div class="info-row">
                <span class="info-label">Year Level:</span>
                <strong>{{ $filters['year'] }}</strong>
            </div>
            <div class="info-row">
                <span class="info-label">Total Entries:</span>
                <strong>{{ $total_entries }}</strong>
            </div>
            <div class="info-row">
                <span class="info-label">Generated:</span>
                <strong>{{ date('M d, Y h:i A') }}</strong>
            </div>
        </div>
    </div>

    @foreach($data as $period)
        <div class="period-header">
            {{ $period['period'] }}
            <span class="period-count">({{ $period['count'] }} entries)</span>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Student ID</th>
                    <th>Name</th>
                    <th>Department</th>
                    <th>Course</th>
                    <th>Year</th>
                    <th>Timestamp</th>
                </tr>
            </thead>
            <tbody>
                @foreach($period['entries'] as $entry)
                    <tr>
                        <td>{{ $entry['student_id'] }}</td>
                        <td>{{ $entry['name'] }}</td>
                        <td>{{ $entry['dept'] }}</td>
                        <td>{{ $entry['course'] }}</td>
                        <td>{{ $entry['year'] }}</td>
                        <td>{{ $entry['timestamp'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach

    <div class="footer">
        <p>This report was automatically generated by the Library QR System</p>
    </div>
</body>
</html>
